version: '3.5'

services:
  web:
    build: ./Machine
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./www:/var/www/html/application

  mysql:
    image: mariadb
    restart: always
    volumes:
     - ./data:/var/lib/mysql
    environment:
     - MARIADB_ROOT_PASSWORD=root
     - MYSQL_DATABASE=skeleton
    links:
     - web

  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis: {}

     
